% This should match the name of the day directory.
day_label = 'Day_B';

data_dir = [ ...
  '/mnt', ...
  '/nfs', ...
  '/clasnetappvm', ...
  '/students', ...
  '/ikhultman', ...
  '/Desktop', ...
  '/power_time_series_analysis', ...
  '/CGRP_power_time_series_analysis', ...
  '/CGRPaba_control_power_results'];

save_dir = [ ...
  '/mnt', ...
  '/nfs', ...
  '/clasnetappvm', ...
  '/students', ...
  '/ikhultman', ...
  '/Desktop', ...
  '/power_time_series_analysis', ...
  '/CGRP_power_time_series_analysis', ...
  '/concatenated_power_ts_CGRPaba_control_data240427'];

exp_phases = { ...
  'B1', ...
  'PI1', ...
  'PI2', ...
  'PI3', ...
  'PI4'};

expected_nonpower_colnames = { ...
  'mouse', ...
  'date', ...
  'freq_band', ...
  'Hz', ...
  'region'};

if iscolumn(exp_phases)
  exp_phases = exp_phases'; 
end

if iscolumn(expected_nonpower_colnames)
  expected_nonpower_colnames = expected_nonpower_colnames'; 
end

n_phases = length(exp_phases);

file_sep = '/';
if ispc
  file_sep = '\';
end

if data_dir(end) ~= file_sep
  data_dir = [data_dir, file_sep];
end

data_dir = [data_dir, day_label, file_sep];

assert(isfolder(data_dir) );

if save_dir(end) ~= file_sep
  save_dir = [save_dir, file_sep];
end

if ~isfolder(save_dir)
  mkdir(save_dir);
end

save_filename = [ ...
  save_dir, ...
  day_label, ...
  '_CGRPaba_control_power_fused_lasso_analysis.csv'];

power_filenames = ls_filenames_w_pattern( ...
  data_dir, ...
  '(?i)^mouse.*\.mat$');

n_fnames = numel(power_filenames);

n_power_vec_check = [];
all_combined_mean_power_ts_table = [];

for fx = 1:n_fnames
  next_filename = [data_dir, power_filenames{fx}];
  next_power_df = load(next_filename);
  next_power_df_vars = fieldnames(next_power_df);
  
  if iscolumn(next_power_df_vars)
    next_power_df_vars = next_power_df_vars';
  end
  
  assert(isempty(setdiff(exp_phases, next_power_df_vars) ));
  leftout_next_power_df_vars = setdiff(next_power_df_vars, exp_phases);

  if ~isempty(leftout_next_power_df_vars)
    warn_msg = [ ...
      'Leaving out the data for the following experimental phases:\n', ...
      repmat('%s\n', 1, numel(leftout_next_power_df_vars) )];

    warning(warn_msg, leftout_next_power_df_vars{:});
  end

  n_power_vec = cellfun( ...
    @(exp_phase) size(next_power_df.(exp_phase), 2), ...
    exp_phases) - ...
    numel(expected_nonpower_colnames);

  if isempty(n_power_vec_check)
    n_power_vec_check = n_power_vec;
  else
    assert(all(n_power_vec == n_power_vec_check) );
  end

  exp_phase_col_ix_table = [ ...
    cumsum([1, n_power_vec(1:(end-1) )]);
    cumsum(n_power_vec)];

  n_tot_power = sum(n_power_vec);
  combined_ts_data = NaN( ...
    size(next_power_df.(exp_phases{1}), 1), ...
    n_tot_power);

  for px = 1:n_phases
    next_phase = exp_phases{px};
    next_tabl_colnames = next_power_df.(next_phase).Properties.VariableNames;
    [~, nonpow_col_ixs] = sort( ...
      intersect( ...
        next_tabl_colnames, ...
        expected_nonpower_colnames) );
    
    for vx = 1:numel(expected_nonpower_colnames)
      next_nonpow_var = expected_nonpower_colnames{vx};

      if ( ...
        isa(next_power_df.(exp_phases{1}).(next_nonpow_var), 'string') || ...
        isa(next_power_df.(exp_phases{1}).(next_nonpow_var), 'cell') )
        assert( ...
          all( ...
            strcmp( ...
              next_power_df.(exp_phases{1}).(next_nonpow_var), ...
              next_power_df.(next_phase).(next_nonpow_var) )));
      else
        assert( ...
          all( ...
            next_power_df.(exp_phases{1}).(next_nonpow_var) == ...
            next_power_df.(next_phase).(next_nonpow_var) ));
      end
    end

    pow_col_ixs = sort( ...
      setdiff( ...
        1:size(next_power_df.(next_phase), 2), ...
        nonpow_col_ixs) );
  
    col_ax = exp_phase_col_ix_table(1,px);
    col_bx = exp_phase_col_ix_table(2,px);
    combined_ts_data(:,col_ax:col_bx) = table2array( ...
      next_power_df.(next_phase)(:,pow_col_ixs) );
  end
  
  next_tabl_colnames = next_power_df.(exp_phases{1}).Properties.VariableNames;
  [~, nonpow_col_ixs] = sort( ...
    intersect( ...
      next_tabl_colnames, ...
      expected_nonpower_colnames) );

  nonpower_table = next_power_df.(exp_phases{1})(:,nonpow_col_ixs);
  
  [grp_ixs, mouse_id, freq_band, region] = findgroups( ...
    nonpower_table.mouse, ...
    nonpower_table.freq_band, ...
    nonpower_table.region);

  if isrow(grp_ixs)
    grp_ixs = grp_ixs';
  end
  
  if isrow(mouse_id)
    mouse_id = mouse_id';
  end

  if isrow(freq_band)
    freq_band = freq_band';
  end
  
  if isrow(region)
    region = region'; 
  end

  group_mean_ts = array2table( ...
    splitapply( ...
      @(pow_mat) mean(pow_mat, 1, 'omitnan'), ...
      combined_ts_data, ...
      grp_ixs) );
  
  mean_power_ts_table = [ ...
    table(mouse_id, freq_band, region), ...
    group_mean_ts];

  if isempty(all_combined_mean_power_ts_table)
    all_combined_mean_power_ts_table = mean_power_ts_table;
  else
    all_combined_mean_power_ts_table = [ ...
      all_combined_mean_power_ts_table;
      mean_power_ts_table];
  end
end

writetable(all_combined_mean_power_ts_table, save_filename);

